### ISSUE TITLE
Reducing ion_beam current 

### ISSUE THREAD

**Issue by Tilaux** [DeMarcoLab/autolamella#30]
Hi,

I am facing the problem, that the script takes pictures for setting marker and lamella position with 7nA. How can I reduce this current? With 7nA is quite difficult to focus and it is destroying my samples.

Best,
Tim

**Comment by bbarad** [comment]
Hi Tim, 

In your config file, the milling_current setting under lamella is I believe the one that controls this. You can also reduce the dwell time to reduce the damage you're doing!

Thanks,
Ben
