### ISSUE TITLE
[BUG] Protocol Validation

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/autolamella#62]
- [x] validate protocol contains all expected keys, add defualt values if not present
- [x] add missing protocol values to protocol converter tools
- [x] deal with missing values in protocol (e.g. thermo application file , tescan preset)
- [x] make sure application file is valid (ThermoFisher)
- [x] make sure preset is valid (TESCAN)
- [ ] Add alignment option in protocol (top level)

**Comment by Rohit-Kannachel** [comment]
tested on demo and tescan simulator, need to check with thermo FIBSEM
