### ISSUE TITLE
[BUG] Lamella info should be saved on creation

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/autolamella#85]
The empty lamella should be added to the list, with the current position and default lamella / fiducial position.

We should be able to navigate between lamella positions without having to save (which really means mill fiducial).

**Comment by LucileNaegele** [comment]
should save anytime anything changes

**Comment by LucileNaegele** [comment]
saving to previous image coordinates for lamella/fiducial and current stage coordinates

**Comment by LucileNaegele** [comment]
default lamella position is whatever the previous one had
